export const knowledgePacks = [
  {
    id: "psychology",
    title: "心理学",
    subtitle: "从双系统思维理解判断与决策",
    meta: "8 个概念 · 约 35 分钟",
    accent: "lavender",
    category: "社会与人文",
    level: "入门",
  },
  {
    id: "management",
    title: "管理学",
    subtitle: "从组织目标到有效协作",
    meta: "10 个概念 · 约 45 分钟",
    accent: "peach",
    category: "商业与管理",
    level: "入门",
  },
  {
    id: "product",
    title: "产品分析",
    subtitle: "建立从需求到方案的分析框架",
    meta: "7 个概念 · 约 30 分钟",
    accent: "pink",
    category: "商业与管理",
    level: "进阶",
  },
  {
    id: "ai-agents",
    title: "AI 智能体",
    subtitle: "理解 Agent、Workflow 与连接器如何协作",
    meta: "9 个概念 · 约 40 分钟",
    accent: "lavender",
    category: "技术与 AI",
    level: "入门",
  },
  {
    id: "economics",
    title: "经济学",
    subtitle: "用供需、激励与边际思维看世界",
    meta: "11 个概念 · 约 50 分钟",
    accent: "peach",
    category: "社会与人文",
    level: "入门",
  },
  {
    id: "critical-thinking",
    title: "批判性思维",
    subtitle: "识别论证、证据与常见逻辑谬误",
    meta: "8 个概念 · 约 36 分钟",
    accent: "pink",
    category: "通用能力",
    level: "入门",
  },
  {
    id: "communication",
    title: "沟通与谈判",
    subtitle: "从倾听、表达走向有效协商",
    meta: "8 个概念 · 约 32 分钟",
    accent: "lavender",
    category: "通用能力",
    level: "入门",
  },
  {
    id: "data-literacy",
    title: "数据素养",
    subtitle: "读懂指标、相关性与数据叙事",
    meta: "10 个概念 · 约 46 分钟",
    accent: "peach",
    category: "技术与 AI",
    level: "入门",
  },
  {
    id: "design-thinking",
    title: "设计思维",
    subtitle: "从同理心到原型验证的完整路径",
    meta: "7 个概念 · 约 30 分钟",
    accent: "pink",
    category: "创意与设计",
    level: "入门",
  },
  {
    id: "personal-finance",
    title: "个人财务",
    subtitle: "理解现金流、风险与复利",
    meta: "9 个概念 · 约 38 分钟",
    accent: "lavender",
    category: "商业与管理",
    level: "入门",
  },
  {
    id: "philosophy",
    title: "哲学入门",
    subtitle: "从好问题开始训练概念辨析",
    meta: "10 个概念 · 约 48 分钟",
    accent: "peach",
    category: "社会与人文",
    level: "入门",
  },
  {
    id: "world-history",
    title: "世界史线索",
    subtitle: "用主题线索连接时代、制度与观念",
    meta: "12 个概念 · 约 55 分钟",
    accent: "pink",
    category: "社会与人文",
    level: "入门",
  },
  {
    id: "behavioral-economics",
    title: "行为经济学",
    subtitle: "理解非理性选择背后的心理规律",
    meta: "9 个概念 · 约 42 分钟",
    accent: "lavender",
    category: "商业与管理",
    level: "进阶",
  },
  {
    id: "systems-thinking",
    title: "系统思维",
    subtitle: "从反馈回路与延迟看懂复杂问题",
    meta: "8 个概念 · 约 38 分钟",
    accent: "peach",
    category: "通用能力",
    level: "进阶",
  },
  {
    id: "storytelling",
    title: "写作与叙事",
    subtitle: "用结构、冲突与细节讲清一个观点",
    meta: "7 个概念 · 约 34 分钟",
    accent: "pink",
    category: "创意与设计",
    level: "入门",
  },
  {
    id: "public-speaking",
    title: "公共表达",
    subtitle: "从观点组织到现场表达的完整练习",
    meta: "8 个概念 · 约 36 分钟",
    accent: "lavender",
    category: "通用能力",
    level: "入门",
  },
];

export const mapNodes = [
  {
    id: "overview",
    title: "双系统思维",
    eyebrow: "核心概念",
    x: 45,
    y: 12,
    status: "mastered",
    description: "人的判断常在快速直觉与缓慢分析两套系统之间切换。",
  },
  {
    id: "system1",
    title: "系统 1",
    eyebrow: "快速 · 自动",
    x: 22,
    y: 34,
    status: "active",
    description: "依靠经验与联想快速反应，节省认知资源，但更容易受偏差影响。",
  },
  {
    id: "system2",
    title: "系统 2",
    eyebrow: "缓慢 · 审慎",
    x: 68,
    y: 34,
    status: "queued",
    description: "需要注意力与逻辑分析，适合复杂、重要或不确定的判断。",
  },
  {
    id: "bias",
    title: "认知偏差",
    eyebrow: "判断捷径",
    x: 12,
    y: 62,
    status: "queued",
    description: "思维捷径在特定情境下会稳定地产生判断误差。",
  },
  {
    id: "loss",
    title: "损失厌恶",
    eyebrow: "价值感知",
    x: 40,
    y: 68,
    status: "queued",
    description: "同等金额下，损失带来的痛苦通常大于收益带来的快乐。",
  },
  {
    id: "anchor",
    title: "锚定效应",
    eyebrow: "初始信息",
    x: 72,
    y: 64,
    status: "queued",
    description: "最先接触的信息会成为锚点，影响之后的估计与判断。",
  },
  {
    id: "framing",
    title: "框架效应",
    eyebrow: "表达方式",
    x: 38,
    y: 84,
    status: "queued",
    description: "同一信息采用不同表达框架时，人们可能做出不同选择。",
  },
  {
    id: "availability",
    title: "可得性偏差",
    eyebrow: "记忆线索",
    x: 77,
    y: 84,
    status: "queued",
    description: "越容易被回忆的信息，越容易被我们高估其发生概率。",
  },
];

export const historyItems = [
  {
    topic: "用户需求与解决方案",
    pack: "产品分析",
    mastery: 76,
    date: "7 月 23 日",
    status: "继续学习",
  },
  {
    topic: "双系统思维",
    pack: "心理学",
    mastery: 36,
    date: "今天",
    status: "学习中",
  },
  {
    topic: "目标与激励机制",
    pack: "管理学",
    mastery: 88,
    date: "7 月 18 日",
    status: "已完成",
  },
];

export const calibrationItems = [
  {
    title: "系统 1 不等于“不理性”",
    detail: "你能说出快速判断的优势，但还需要补充它在哪些情境下是有效的。",
    type: "待澄清",
    date: "今天 10:18",
  },
  {
    title: "需求与方案的边界",
    detail: "你能区分需求与方案，但对“同一需求的不同表达”判断标准仍不够清晰。",
    type: "待验证",
    date: "7 月 23 日",
  },
  {
    title: "内在动机与外在激励",
    detail: "已通过生活案例完成复述，概念关系表达准确。",
    type: "已校准",
    date: "7 月 18 日",
  },
];

export const feedbackByMode = {
  feynman: {
    recap:
      "我先复述一下你的意思：系统 1 像自动驾驶，会依靠熟悉的经验快速得出判断；系统 2 则需要我们停下来主动分析。",
    probe:
      "我想再追问一处：如果系统 1 并不总是错误，你能举一个“快速判断反而更有效”的情境吗？",
  },
  socratic: {
    recap:
      "我听到你的核心判断是：复杂问题应该交给系统 2，而简单问题可以依赖系统 1。",
    probe:
      "让我们检查这个假设：问题的“复杂程度”是谁判断的？这个判断本身会不会已经受系统 1 影响？",
  },
};
